// Centralised content data — swap images and copy here without touching components.
import hero from "@/assets/hero-living.jpg";
import kitchen from "@/assets/project-kitchen.jpg";
import bedroom from "@/assets/project-bedroom.jpg";
import foyer from "@/assets/project-foyer.jpg";
import dining from "@/assets/project-dining.jpg";
import materials from "@/assets/materials.jpg";
import office from "@/assets/project-office.jpg";
import noor from "@/assets/portrait-noor.jpg";
import serviceLivingRoom from "@/assets/service-living-room.png";
import serviceCeiling from "@/assets/service-ceiling.png";
import serviceFurniture from "@/assets/service-furniture.png";
import serviceTurnkey from "@/assets/service-turnkey.png";
import serviceStorage from "@/assets/service-storage.png";
import servicesHeaderDecor from "@/assets/services-header-decor.png";
export const images = { hero, kitchen, bedroom, foyer, dining, materials, office, noor, servicesHeaderDecor };
export const projects = [
    //fhjhskfh
    {
        slug: "the-travertine-villa",
        name: "The Travertine Villa",
        location: "Greater Noida West",
        type: "Turnkey Residential",
        category: "Turnkey",
        year: "2025",
        area: "3,200 sq ft",
        cover: hero,
        gallery: [hero, dining, bedroom, materials],
        vision: "A young family relocating from Singapore wanted a home that read as warm and grounded, but unmistakably modern. The challenge: a 3,200 sq ft villa on a corner plot with strong directional light that needed careful tempering.",
        approach: "We anchored the living spaces in travertine and dark walnut — materials that age with grace — then layered linen, brass, and hand-loomed textiles for warmth. Lighting was designed in three tiers so the home reads differently at every hour.",
        client: {
            quote: "Mr. Noor understood our vision before we could fully articulate it. The result is a home that feels entirely ours — delivered exactly to schedule.",
            author: "Ananya & Vikram S. · Villa Interior",
        },
    },
    {
        slug: "fluted-walnut-kitchen",
        name: "Fluted Walnut Kitchen",
        location: "Noida",
        type: "Modular Kitchen",
        category: "Kitchens",
        year: "2025",
        area: "320 sq ft",
        cover: kitchen,
        gallery: [kitchen, materials, dining],
        vision: "An apartment kitchen for a family that entertains weekly. The client wanted the kitchen to act as both workshop and stage — quietly functional in daily use, theatrical when guests arrive.",
        approach: "Fluted dark walnut joinery wraps three walls; the island is a single slab of Calacatta. Brushed brass hardware, warm under-cabinet light, and a discreetly hidden pantry resolve the tension between calm and capability.",
        client: {
            quote: "The most-discussed room by every guest. Every detail — lighting, hardware, storage — has been thought through with extraordinary care.",
            author: "Priya K. · Modular Kitchen · Ghaziabad",
        },
    },
    {
        slug: "the-soft-room",
        name: "The Soft Room",
        location: "Gurgaon",
        type: "Master Bedroom",
        category: "Bedrooms",
        year: "2024",
        area: "480 sq ft",
        cover: bedroom,
        gallery: [bedroom, materials, foyer],
        vision: "A primary bedroom for a couple who travel extensively. They wanted the room to feel like a private suite — restorative, hushed, free of digital intrusion.",
        approach: "An upholstered taupe boucle wall reduces ambient noise and softens the geometry. Walnut floors, layered linens, and a single sculptural reading lamp do the rest. There is no overhead light — only pools of warmth.",
        client: {
            quote: "We sleep better. That sounds simple. It is the single most valuable thing a designer has ever given us.",
            author: "Mr. & Mrs. K. · Master Bedroom · Gurgaon",
        },
    },
    {
        slug: "the-rotunda-foyer",
        name: "The Rotunda Foyer",
        location: "Delhi",
        type: "Entry & Circulation",
        category: "Residential",
        year: "2024",
        area: "240 sq ft",
        cover: foyer,
        gallery: [foyer, hero, dining],
        vision: "A foyer that needed to do three things: receive guests, resolve an awkward circular geometry, and signal — without ostentation — the quality of what lay beyond.",
        approach: "A curved travertine wall absorbs the geometry. A single sculptural console, one artwork, and a slim brass ceiling reveal are the only gestures. Restraint is what makes the moment land.",
        client: {
            quote: "Every visitor pauses here. That is exactly what we asked for.",
            author: "The R. Family · Delhi",
        },
    },
    {
        slug: "evening-dining",
        name: "Evening Dining",
        location: "Greater Noida",
        type: "Dining & Entertainment",
        category: "Living Rooms",
        year: "2025",
        area: "360 sq ft",
        cover: dining,
        gallery: [dining, hero, materials],
        vision: "A formal dining room that needed to seat ten without feeling cavernous when it was just the family of four eating breakfast.",
        approach: "A solid oak table, a sculptural cluster chandelier, and a fluted screen that closes the room down to intimate scale on quiet nights. The art wall does the rest of the conversation.",
        client: {
            quote: "Dinner parties have become an event again. The room makes the evening.",
            author: "Mrs. M. · Greater Noida",
        },
    },
    {
        slug: "the-private-library",
        name: "The Private Library",
        location: "Noida",
        type: "Home Office",
        category: "Offices",
        year: "2024",
        area: "280 sq ft",
        cover: office,
        gallery: [office, materials, foyer],
        vision: "A working library for a senior partner who reads three hours every morning. The room needed to hold 1,200 books, a working desk, and a lounge chair that genuinely invites sitting.",
        approach: "Built-in dark walnut shelving wraps two walls. A leather lounge chair anchors the corner. Lighting is layered: a brass desk lamp, a single floor lamp, and indirect cove warmth for the books.",
        client: {
            quote: "I have started arriving early at home, just to spend time here.",
            author: "Mr. A. · Noida",
        },
    },
];
export const services = [
    {
        slug: "residential-interior-design",
        name: "Residential Interior Design",
        shortName: "Residential Design",
        tagline: "Whole-home interiors, designed and delivered end-to-end.",
        intro: "A complete residential design service for owners commissioning a single, considered interior for their primary home — from spatial planning and concept development to material specification and final handover. Every decision passes through Mr. Noor's review; every milestone is supervised by Mr. Nadeem.",
        scope: [
            "Detailed brief and lifestyle assessment",
            "Spatial planning and layout strategy",
            "Concept boards, palette and 3D visualisations",
            "Bespoke joinery, furniture and lighting design",
            "Material and finish specification",
            "On-site execution and quality supervision",
            "Final styling, handover and care guide",
        ],
        philosophy: "A home is not a project. A home is a daily environment for the life you have built. We design slowly, decide thoughtfully, and finish completely.",
        cover: hero,
    },
    {
        slug: "modular-kitchen-design",
        name: "Modular Kitchen Design",
        shortName: "Modular Kitchens",
        tagline: "Kitchens designed for how you actually cook, entertain, and live.",
        intro: "From layout planning to precision hardware, our kitchens are built around real cooking patterns — not catalogue presets. We design the workflow first, then design the room around it.",
        scope: [
            "Kitchen layout planning (U, L, parallel, island, galley)",
            "Custom modular unit design with CAD drawings",
            "Premium shutter material selection",
            "Countertop and splashback specification",
            "Hardware and appliance integration",
            "Lighting and ventilation design",
            "On-site fabrication and quality verification",
        ],
        philosophy: "A kitchen earns its keep at 7am, not just at a dinner party. Beauty must survive daily use.",
        cover: kitchen,
    },
    {
        slug: "luxury-living-room-interiors",
        name: "Luxury Living Room Interiors",
        shortName: "Living Rooms",
        tagline: "Living rooms composed for conversation, for stillness, for guests.",
        intro: "We design living rooms as the social heart of the home — composed for movement and pause, for the family alone and for twelve guests, for morning light and for evening warmth.",
        scope: [
            "Spatial layout and circulation",
            "Custom seating and upholstery",
            "Joinery, media and feature walls",
            "Lighting design — ambient, task, accent",
            "Rug, art, and accessory curation",
            "Acoustic and material balance",
        ],
        philosophy: "A living room is the only room everyone in the family uses every day. It must feel inevitable.",
        cover: serviceLivingRoom,
    },
    {
        slug: "luxury-bedroom-design",
        name: "Luxury Bedroom Design",
        shortName: "Bedrooms",
        tagline: "Bedrooms as private suites — restorative, hushed, intimate.",
        intro: "We treat the bedroom as a sanctuary. Materials, lighting, and acoustics are designed for sleep first. Aesthetics follow from there.",
        scope: [
            "Layout and wardrobe planning",
            "Upholstered walls and headboards",
            "Bespoke joinery and dressing areas",
            "Layered, dimmable lighting design",
            "Linen, drape and textile curation",
            "Ensuite coordination",
        ],
        philosophy: "If the room does not improve your sleep, the design has failed.",
        cover: bedroom,
    },
    {
        slug: "false-ceiling-lighting-design",
        name: "False Ceiling & Lighting Design",
        shortName: "Ceilings & Lighting",
        tagline: "Lighting as architecture. Ceilings as composition.",
        intro: "Lighting is the most under-considered element in Indian interiors. We design lighting as the first decision, not the last — with ceilings composed to support it.",
        scope: [
            "Architectural ceiling design",
            "Three-tier lighting strategy (ambient, task, accent)",
            "Cove, recessed and decorative integration",
            "Dimming and scene control",
            "Daylight and circadian planning",
        ],
        philosophy: "A room is what its light makes it.",
        cover: serviceCeiling,
    },
    {
        slug: "custom-furniture-design",
        name: "Custom Furniture Design",
        shortName: "Custom Furniture",
        tagline: "Furniture made for your space, by craftspeople we have worked with for years.",
        intro: "When the catalogue does not answer the question, we design the answer. Each piece is detailed, fabricated, and finished under our supervision.",
        scope: [
            "Concept and detail drawings",
            "Material and finish selection",
            "Prototype and sample review",
            "Workshop fabrication oversight",
            "On-site installation and finishing",
        ],
        philosophy: "Bespoke is the original sustainability. Build it once, build it right.",
        cover: serviceFurniture,
    },
    {
        slug: "turnkey-interior-solutions",
        name: "Turnkey Interior Solutions",
        shortName: "Turnkey Solutions",
        tagline: "From empty shell to move-in ready. One studio. One accountability.",
        intro: "A complete turnkey delivery for clients who want one team accountable for design, procurement, fabrication, execution, and final styling. We hand you the keys.",
        scope: [
            "Full scope brief and feasibility",
            "Design development and approvals",
            "Civil, electrical and plumbing coordination",
            "Procurement and vendor management",
            "On-site project management",
            "Final styling and move-in handover",
            "Documented warranty and care guide",
        ],
        philosophy: "Turnkey means one number to call, one team to trust, one date to count down to.",
        cover: serviceTurnkey,
    },
    {
        slug: "office-commercial-interiors",
        name: "Office & Commercial Interiors",
        shortName: "Office Interiors",
        tagline: "Workplaces designed for focus, presence, and the brand they represent.",
        intro: "Senior offices, boutique studios, and client-facing commercial spaces — designed with the same restraint as our residential work, with attention to acoustics, lighting, and material durability.",
        scope: [
            "Workplace strategy and zoning",
            "Reception and client area design",
            "Bespoke workstation and meeting joinery",
            "Acoustic and lighting design",
            "Brand-led material palette",
        ],
        philosophy: "Your office is your most under-used brand asset.",
        cover: office,
    },
    {
        slug: "space-planning-storage",
        name: "Space Planning & Storage",
        shortName: "Space & Storage",
        tagline: "Planning that solves the rooms you actually live in.",
        intro: "Often the room does not need a redesign — it needs a re-plan. Our space planning service rethinks layouts and storage to recover function without rebuilding.",
        scope: [
            "Lifestyle and storage audit",
            "Revised layouts and circulation",
            "Concealed storage solutions",
            "Modular wardrobe and utility design",
            "Implementation drawings",
        ],
        philosophy: "Storage is the most luxurious thing in a home. It is what creates the calm.",
        cover: serviceStorage,
    },
    {
        slug: "tv-unit-feature-wall-design",
        name: "TV Unit & Feature Wall Design",
        shortName: "Feature Walls",
        tagline: "Feature walls that anchor the room without dominating it.",
        intro: "We design feature walls as composition, not as decoration — with material, light, and proportion working together to give the room a centre.",
        scope: [
            "Concept and proportion studies",
            "Material and finish specification",
            "Integrated lighting and cable management",
            "Custom joinery and installation",
            "Art and object styling",
        ],
        philosophy: "A feature wall should reward you on the hundredth day, not just the first.",
        cover: dining,
    },
];
export const STUDIO = {
    name: "Souvenir Interiors",
    phone: "+91 81782 32328",
    whatsapp: "+918178232328",
    email: "welcome@souvenirinteriors.com",
    address: "Galaxy Diamond Plaza, Sector 4",
    addressLine2: "Opposite Gaur City Mall, Greater Noida West",
    hours: "Mon–Sat · 10:00 AM – 7:00 PM",
};
